//
//  PrimaryExampleTableCell.swift
//  UITableViewUsageExample
//
//  Created Volodymyr Andriienko on 15.03.2021.
//
//  Template generated by VAndrJ
//

import UIKit

class PrimaryExampleTableCell: UITableViewCell {
    private let watermarkLabel: UILabel = {
        let label = UILabel()
        label.text = "Example"
        label.textColor = .lightGray
        label.sizeToFit()
        return label
    }()
    
    override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
        super.init(style: .subtitle, reuseIdentifier: reuseIdentifier)
        addElements()
        configure()
    }
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        watermarkLabel.center = contentView.center
    }
    
    private func configure() {
        watermarkLabel.transform = CGAffineTransform(rotationAngle: -.pi / 5)
    }
    
    private func addElements() {
        contentView.addSubview(watermarkLabel)
    }
}
