//
//  PrimaryExampleCellObject+UITableView.swift
//  UITableViewUsageExample
//
//  Created Volodymyr Andriienko on 15.03.2021.
//
//  Template generated by VAndrJ
//

import UIKit

extension PrimaryExampleCellObject: VACellObjectTableProtocol {
    var cellClass: AnyClass {
        return PrimaryExampleTableCell.self
    }
    
    func configure(cell: UITableViewCell) {
        let cell = cell as! PrimaryExampleTableCell
        cell.textLabel?.text = title
        cell.detailTextLabel?.text = description
    }
}

extension PrimaryExampleCellObject: VACellObjectHeightTableProtocol {
    
    func getHeight(bounding rect: CGRect) -> CGFloat {
        return 100
    }
}
