//
//  SecondaryExampleCellObject+UITableView.swift
//  UITableViewUsageExample
//
//  Created Volodymyr Andriienko on 15.03.2021.
//
//  Template generated by VAndrJ
//

import UIKit

extension SecondaryExampleCellObject: VACellObjectTableProtocol {
    var cellClass: AnyClass {
        return SecondaryExampleTableCell.self
    }
    
    func configure(cell: UITableViewCell) {
        let cell = cell as! SecondaryExampleTableCell
        cell.textLabel?.text = title
    }
}

extension SecondaryExampleCellObject: VACellObjectHeightTableProtocol {
    
    func getHeight(bounding rect: CGRect) -> CGFloat {
        return /*@START_MENU_TOKEN@*/UITableView.automaticDimension/*@END_MENU_TOKEN@*/
    }
}
